module.exports = {
    // Main Tables
    ACADEMIC_TOOLS: "Academic Tools",
    ADVENTURING_GEAR: "Adventuring Gear",
    ALCHEMICAL_SUBSTANCES: "Alchemical Substances",
    ARMOR: 'Armor',
    BEVERAGES: 'Beverages',
    CLOTHING: 'Clothing',
    ENTERTAINMENT: 'Entertainment',
    FABRICS_AND_ROPES: 'Fabrics & Ropes',
    FOOD: 'Food',
    HOUSEHOLD_ITEMS: 'Household Items',
    ILLUMINATION: 'Illumination',
    JEWELRY: 'Jewelry',
    MEDICAL_TOOLS: 'Medical Tools',
    MUSICAL_INSTRUMENTS: 'Musical Instruments',
    PERSONAL_CONTAINERS: 'Personal Containers',
    RAW_GOODS: 'Raw Good',
    RELIGIOUS_ITEMS: 'Religious Items',
    SHIELDS: 'Shields',
    TRADE_TOOLS: 'Trade Tools',
    WEAPONS: 'Weapons',
    WORKS_OF_ART: 'Works of Art',
    ROLL_TWICE: 'Roll Twice and Combine',
    // Base Materials
    METAL: 'Metal',
    CLOTH: 'Cloth',
    LEATHER: 'Leather',
    FUR: 'Fur',
    FUR_OR_LEATHER: 'Fur or Leather',
    WOOD: 'Wood',
    PAPER_PRODUCT: 'Paper Product',
    PARCHMENT: 'Parchment',
    VELLUM: 'Vellum',
    WAX: 'Wax',
    STONE_EARTHWORK: 'Stone/Earthwork',
    // Clothing Subtables
    ACCESSORIES: 'Accessories',
    BODY: 'Body',
    FOOTWEAR: 'Footwear',
    HEADGEAR: 'Headgear',
    // Food Subtables
    PREPPED_FOOD: 'Prepped Food',
    BREAD: 'Bread',
    FRUIT_AND_VEGATABLES: 'Fruit & Vegetables',
    PROTEIN: 'Protein',
    NUTS: 'Nuts',
    SPICES_AND_SEASONINGS: 'Spices & Seasonings',
    // Weapon Subtables
    AXES: 'Axes',
    POLEARMS: 'Polearms',
    SIDEARMS: 'Sidearms',
    SWORDS: 'Swords',
    TRAUMA: 'Trauma',
    THROWN: 'Thrown',
    MECHANICAL_RANGED: 'Mechanical Ranged',
    FIREARMS: 'Firearms',
    // Misc Subtables
    SIZE: 'Size',
    ADJECTIVES: 'Adjectives',
    COLORS: 'Colors',
    ENGRAVINGS: 'Engravings',
    GEMS: 'Gems',
    QUIRKS: 'Quirks',
    // Exotic Subtables
    EXOTIC_CLOTH: 'Exotic Cloth',
    EXOTIC_METAL: 'Exotic Metal',
    EXOTIC_STONE_EARTHWORK: 'Exotic Stone/Earthwork',
    EXOTIC_WOOD: 'Exotic Wood',
    // Detail Subtables
    SIZE: 'Size',
    ADJECTIVES: 'Adjectives',
    COLORS: 'Colors',
    WEAPON_COLORS: 'Weapon Colors',
    EXPLOSION_COLORS: 'Explosion Colors',
    ENGRAVINGS: 'Engravings',
    STITCHINGS: 'Stitchings',
    GEMS: 'Gems',
    QUIRKS: 'Quirks',
    RACE_OF_ORIGIN: 'Race of Origin',
    ANIMAL_SUBTYPE: 'Animal Subtype',
    ANIMAL_AIR: 'Animal Air',
    ANIMAL_LAND: 'Animal Land',
    ANIMAL_WATER: 'Animal Water',
    BODY_PARTS: 'Body Parts',
    BODY_HEAD: 'Head Parts',
    BODY_ARM: 'Arm Parts',
    BODY_BODY: 'Body Body',
    BODY_LEGS: 'Leg Parts',
    ENGRAVING_TYPE_WITH_GEMS: 'Engraving Type with Gems',
    ENGRAVING_TYPE_WITH_NO_GEMS: 'Engraving Type Without Gems',
    STITCHING_TYPE: 'Stitching Type',
    SUBJECT: 'Subject',
    PERSONS: 'Persons',
    EVENTS: 'Events',
    EVENTS_TIMEPERIOD: 'Time Period',
    EVENTS_SUBJECT: 'Event Subject',
    GEM_SIZE: 'Gem Size',
    GEM_SHAPE: 'Gem Shape',
    GEM_TYPE: 'Gem Type',
    // Other
    PRICE: 'Price',
    AMOUNT_MAX: 'Amount_Max',
    AMOUNT_MIN: 'Amount_Min',
    TYPE: 'Type',
    MULTIPLIER: 'Multiplier'
}