module.exports = {
    // Main Tables
    ACADEMIC_TOOLS: "Academic Tools",
    ADVENTURING_GEAR: "Adventuring Gear",
    ALCHEMICAL_SUBSTANCES: "Alchemical Substances",
    ARMOR: 'Armor',
    BEVERAGES: 'Beverages',
    CLOTHING: 'Clothing',
    ENTERTAINMENT: 'Entertainment',
    FABRICS_AND_ROPES: 'Fabrics & Ropes',
    FOOD: 'Food',
    HOUSEHOLD_ITEMS: 'Household Items',
    ILLUMINATION: 'Illumination',
    JEWELRY: 'Jewelry',
    MEDICAL_TOOLS: 'Medical Tools',
    MUSICAL_INSTRUMENTS: 'Musical Instruments',
    PERSONAL_CONTAINERS: 'Personal Containers',
    RAW_GOODS: 'Raw Goods',
    RELIGIOUS_ITEMS: 'Religious Items',
    SHIELDS: 'Shields',
    TRADE_TOOLS: 'Trade Tools',
    WEAPONS: 'Weapons',
    WORKS_OF_ART: 'Works of Art',
    ROLL_TWICE: 'Roll Twice and Combine',
    // Base Materials
    METAL: 'Metal',
    CLOTH: 'Cloth',
    LEATHER: 'Leather',
    WOOD: 'Wood',
    PAPER_PRODUCT: 'Paper Product',
    WAX: 'Wax',
    STONE_EARTHWORK: 'Stone/Earthwork',
    // Subtables
    SIZE: 'Size',
    ADJECTIVES: 'Adjectives',
    COLORS: 'Colors',
    ENGRAVINGS: 'Engravings',
    GEMS: 'Gems',
    QUIRKS: 'Quirks',
}